### ISSUE TITLE
Adjust and validate large box label template

### ISSUE THREAD

**Issue by boulund** [ctmrbio/print_ctmr_labels#3]
The Large Box label template hasn't been tested and most likely needs to be adjusted and verified to be working well. 

At least the following points must be addressed:

- Starting coordinates for each line
- Font sizes need to be optimized
- Optimal line lengths for centering need to be determined

**Comment by kimchi-jjigae** [comment]
Fixed and added QR codes!
The line lengths for centering haven't been looked at though, but I'm not sure this is necessary
